### ISSUE TITLE
Registration page clarification

### ISSUE THREAD

**Issue by mattwojo** [craigloewen-msft/GitGudIssues#2]
**
![image](https://user-images.githubusercontent.com/7566797/143139576-eed79791-a7b3-4bb5-9a24-3684772e6777.png)
**

Currently the registration page asks for:

- Username
- Email
- Github username
- Password
- Confirm password

This leaves some ambiguity... specifically whether this is asking for your Github password, or for you to create a new password that will be used with this service.

My recommendation is to change this to:

- Github username  >>>check whether this already exists in the registration system, deny registration if so.
- Email (to receive notifications)
- Create your GitGud username
- Create your GitGud password
- Confirm your GitGud password

**Comment by craigloewen-msft** [comment]
Does this look better @mattwojo ?

<img width="373" alt="image" src="https://user-images.githubusercontent.com/42221804/143293074-69e3f7a5-e7b1-4f67-8de7-4f9394e2cc97.png">

**Comment by mattwojo** [comment]
So much better! These updates make it clear what is being asked for and what is being created.

**Comment by mattwojo** [comment]
*The only thing I might consider adding is whether the GitGudIssues username needs to be different than your GitHub username. (And use "GitHub" capitalization, especially since you're using GitGud capitalization).
